#!/bin/bash

# ==============================================================================
#  BRITSYNC CRM — VPS MULTI-PROJECT SUBDOMAIN DEPLOYMENT SCRIPT
# ==============================================================================

# Exit on error
set -e

# Color codes for output
GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m' # No Color

echo -e "${BLUE}======================================================================${NC}"
echo -e "${GREEN}             ____       _ _                                           ${NC}"
echo -e "${GREEN}            | __ ) _ __(_) |_ ___ _   _ _ __   ___                    ${NC}"
echo -e "${GREEN}            |  _ \| '__| | __/ __| | | | '_ \ / __|                   ${NC}"
echo -e "${GREEN}            | |_) | |  | | |_ \__ \ |_| | | | | (__                    ${NC}"
echo -e "${GREEN}            |____/|_|  |_|\__|___/\__, |_| |_|\___|                   ${NC}"
echo -e "${GREEN}                                  |___/                               ${NC}"
echo -e "${BLUE}        Britsync CRM - VPS Multi-Project Safe Deployment Script        ${NC}"
echo -e "${BLUE}======================================================================${NC}"

# 1. Check prerequisites
echo -e "\n${BLUE}[1/5] Verifying prerequisites...${NC}"
if ! [ -x "$(command -v docker)" ]; then
  echo -e "${RED}Error: docker is not installed. Please install Docker first.${NC}" >&2
  exit 1
fi
echo -e "${GREEN}✓ Docker & Docker Compose are installed.${NC}"

# Define command alias for docker compose
DOCKER_COMPOSE="docker compose"
if ! docker compose version >/dev/null 2>&1; then
  DOCKER_COMPOSE="docker-compose"
fi

# 2. Get Subdomain Configuration
echo -e "\n${BLUE}[2/5] Domain Configuration...${NC}"
read -p "Enter your target subdomain (e.g. crm.britsyncai.com): " DOMAIN
if [ -z "$DOMAIN" ]; then
  echo -e "${RED}Error: Domain name cannot be empty.${NC}"
  exit 1
fi

# Verify SSL cert exists
SSL_CERT_PATH="/etc/letsencrypt/live/$DOMAIN/fullchain.pem"
SSL_KEY_PATH="/etc/letsencrypt/live/$DOMAIN/privkey.pem"

if [ ! -f "$SSL_CERT_PATH" ]; then
  echo -e "${YELLOW}Warning: Certbot fullchain.pem not found at $SSL_CERT_PATH.${NC}"
  echo -e "${YELLOW}Please make sure you have successfully generated the Let's Encrypt certificate.${NC}"
  read -p "Press Enter to continue anyway if you will resolve this manually, or Ctrl+C to cancel..."
fi

# 3. Create .env.production file
echo -e "\n${BLUE}[3/5] Setting up environment files...${NC}"
if [ -f "apps/backend/.env" ]; then
  echo -e "Copying existing backend .env to root .env.production..."
  cp apps/backend/.env .env.production
else
  echo -e "Creating .env.production from template..."
  cp apps/backend/.env.example .env.production
fi

# Update Domain URLs in env files
sed -e "s|APP_URL=.*|APP_URL=https://$DOMAIN|g" \
    -e "s|FRONTEND_URL=.*|FRONTEND_URL=https://$DOMAIN|g" \
    -e "s|BACKEND_URL=.*|BACKEND_URL=https://$DOMAIN/api|g" \
    .env.production > .env.production.tmp
mv .env.production.tmp .env.production

# Sync to package and root
cp .env.production packages/database/.env
cp .env.production .env

echo -e "${GREEN}✓ Environment configurations generated and updated for $DOMAIN.${NC}"

# 4. Generate and Enable Host-Level Nginx Configuration
echo -e "\n${BLUE}[4/5] Configuring host-level Nginx reverse proxy...${NC}"
NGINX_CONF_TEMP="/tmp/nginx_${DOMAIN}.conf"

# Generate Nginx Server Block
cat <<EOF > "$NGINX_CONF_TEMP"
server {
    listen 80;
    server_name $DOMAIN;

    # Redirect all HTTP requests to HTTPS
    return 301 https://\$host\$request_uri;
}

server {
    listen 443 ssl http2;
    server_name $DOMAIN;

    # SSL Certs generated by Certbot
    ssl_certificate $SSL_CERT_PATH;
    ssl_certificate_key $SSL_KEY_PATH;

    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers HIGH:!aNULL:!MD5;
    ssl_prefer_server_ciphers on;

    # Proxy API requests to backend NestJS container (Port 3001)
    location /api/ {
        proxy_pass http://127.0.0.1:3001/;
        proxy_http_version 1.1;
        proxy_set_header Upgrade \$http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
    }

    # Proxy socket.io/websocket traffic
    location /socket.io/ {
        proxy_pass http://127.0.0.1:3001/socket.io/;
        proxy_http_version 1.1;
        proxy_set_header Upgrade \$http_upgrade;
        proxy_set_header Connection "Upgrade";
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
    }

    # Proxy all other requests to Next.js Frontend container (Port 3000)
    location / {
        proxy_pass http://127.0.0.1:3000;
        proxy_http_version 1.1;
        proxy_set_header Upgrade \$http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
    }
}
EOF

echo -e "Writing Nginx configuration to /etc/nginx/sites-available/$DOMAIN..."
sudo cp "$NGINX_CONF_TEMP" "/etc/nginx/sites-available/$DOMAIN"
rm "$NGINX_CONF_TEMP"

# Create symlink to enable site
if [ ! -f "/etc/nginx/sites-enabled/$DOMAIN" ]; then
  echo -e "Enabling site in Nginx..."
  sudo ln -s "/etc/nginx/sites-available/$DOMAIN" "/etc/nginx/sites-enabled/"
fi

# Test and reload Nginx
echo -e "Testing Nginx configuration..."
sudo nginx -t
echo -e "Reloading Nginx web server..."
sudo systemctl reload nginx

echo -e "${GREEN}✓ Host-level Nginx reverse-proxy is configured and running.${NC}"

# 5. Build and Start Containerized Services
echo -e "\n${BLUE}[5/5] Building and starting Docker containers...${NC}"
$DOCKER_COMPOSE -f docker-compose.vps.yml down
$DOCKER_COMPOSE -f docker-compose.vps.yml up -d --build

echo -e "${GREEN}✓ Docker containers built and started successfully.${NC}"

# 6. Database Migration & Seeding
echo -e "\n${BLUE}[6/6] Synchronizing database & seeding demo records...${NC}"
echo -e "Waiting for backend service to become healthy..."
sleep 15

# Push Prisma Schema Indexes
echo -e "Pushing schema index definitions to MongoDB..."
$DOCKER_COMPOSE -f docker-compose.vps.yml exec -T backend npx prisma db push --schema=packages/database/prisma/schema.prisma

# Seed demo data
echo -e "Seeding default data (this may take a moment)..."
if [ -x "$(command -v node)" ]; then
  pnpm install --filter @blackdesk/database
  node scripts/seed-demo-data.js
else
  docker run --rm \
    --network crm-blackdesk_britsync-vps-internal \
    -v "$(pwd):/app" \
    -w /app \
    node:20-alpine sh -c "npm install -g pnpm && pnpm install --filter @blackdesk/database && node scripts/seed-demo-data.js"
fi

echo -e "\n${GREEN}======================================================================${NC}"
echo -e "${GREEN} 🎉 Britsync CRM DEPLOYED ON VPS SUCCESSFULLY!${NC}"
echo -e " Domain: ${BLUE}https://$DOMAIN${NC}"
echo -e " Log files: docker compose -f docker-compose.vps.yml logs -f${NC}"
echo -e " Preseeded credentials:${NC}"
echo -e "   - Admin: ${YELLOW}admin@Britsync.com${NC} / password123${NC}"
echo -e "   - Client: ${YELLOW}client@Britsync.com${NC} / password123${NC}"
echo -e "${GREEN}======================================================================${NC}"
EOF
